### ISSUE TITLE
滚动界面很卡。 希望能优化，随便好集成！ 谢谢作者

### ISSUE THREAD

**Issue by songhongkang** [chenfanfang/CollectionsOfExample#1]
你好，请问是 点击状态栏自动滚动到顶部 ，的那个类吗？（或者和我说下是哪个例子） 能具体说明下 你卡的情况吗

**Comment by chenfanfang** [comment]
你好，请问是 点击状态栏自动滚动到顶部  ，的那个类吗？（或者和我说下是哪个例子）   能具体说明下  你卡的情况吗

**Comment by chenfanfang** [comment]
你好，请问是 点击状态栏自动滚动到顶部 ，的那个类吗？（或者和我说下是哪个例子） 能具体说明下 你卡的情况吗
